
let ns_regex_flags = 0;
const XM_TERM_TAG_DEFAULT_GRAPH = 1 << ns_regex_flags++;
const XM_TERM_TAG_NODE_NAMED = 1 << ns_regex_flags++;
const XM_TERM_TAG_NODE_BLANK = 1 << ns_regex_flags++;
const XM_TERM_TAG_LITERAL_SIMPLE = 1 << ns_regex_flags++;
const XM_TERM_TAG_LITERAL_LANGUAGED = 1 << ns_regex_flags++;
const XM_TERM_TAG_LITERAL_DATATYPED = 1 << ns_regex_flags++;
const XM_TERM_TAG_NODE = XM_TERM_TAG_NODE_NAMED | XM_TERM_TAG_NODE_BLANK;
const XM_TERM_TAG_LITERAL = XM_TERM_TAG_LITERAL_SIMPLE | XM_TERM_TAG_LITERAL_LANGUAGED | XM_TERM_TAG_LITERAL_DATATYPED;
const XM_TERM_TAG_ANY = XM_TERM_TAG_DEFAULT_GRAPH | XM_TERM_TAG_NODE | XM_TERM_TAG_LITERAL;

module.exports = {
	XM_TERM_TAG_DEFAULT_GRAPH,
	XM_TERM_TAG_NODE_NAMED,
	XM_TERM_TAG_NODE_BLANK,
	XM_TERM_TAG_LITERAL_SIMPLE,
	XM_TERM_TAG_LITERAL_LANGUAGED,
	XM_TERM_TAG_LITERAL_DATATYPED,
	XM_TERM_TAG_NODE,
	XM_TERM_TAG_LITERAL,
	XM_TERM_TAG_ANY,
};
